### ISSUE TITLE
Scenes without speaking characters (but stage direction) are not shown in analysis

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaAnalysis#99] opened 2018-06-19 10:17 UTC
Segmentation, e.g. `figureStatistics(x, segment="Scene")`, seems to produce errors in some cases:

gdc:n750.0 should have 12 Scene in Act I and 20 Scenes in Act III; fstat shows 11 in Act I and 18 in Act III.
DictionaryStatistics() however produces the expected number of scenes.

The problem is not present in all dramas, e.g. it works fine for rksp.0

**Comment by nilsreiter** [comment] 2018-06-21 11:23
It seems the numbering of the scenes is off. Scene 11 in the `figureStatistics()` output contains "Siegmund" and "Lottchen", who are actually speaking in Scene 12 (`gdc:n750.0`).

**Comment by nilsreiter** [comment] 2018-06-21 11:31
This is caused by the seventh scene. It's present in the TEI, but it doesn't have a `sp` element and therefore no speaker:
```xml
        <div>
          <div>
            <desc>
              <title>7. Auftritt</title>
            </desc>
          </div>
          <div type="text">
            <div type="h4">
              <head>Siebenter Auftritt</head>
              <stage>
                <hi>Julchen allein.</hi>
              </stage>
              <p>Wie? Er geht? Aber warum bin ich so unruhig? Ich liebe ihn ja nicht ... Nein, ich bin ihm nur gewogen. Es ist doch ein unerträglicher Stolz, daß er mich verläßt. Aber habe ich ihn etwan beleidiget? Er ist ja sonst so vernünftig und so großmütig ... Nein, nein, er liebt mich nicht. Es muß Verstellung gewesen sein. Ich habe heute ein recht mürrisches Wesen. <hi>Lottchen tritt unvermerkt herein.</hi> Wenn ich nur meine Laute hier hätte, ich wollte ...</p>
            </div>
          </div>
        </div>
```

This is scene is not event represented in the CSV output and therefore the first act only has 11 scenes.

There is no quick fix available, but we should address this in conjunction with taking nebentext into account: https://github.com/orgs/quadrama/projects/8.

**Comment by nilsreiter** [comment] 2019-03-12 12:17
This is actually a bug in the XML and will be fixed there.

**Closed as completed** 2019-03-12 17:22 UTC
Labels: bug
